# 4.8. Grouping Data & Aggregating Variables

In [1]:
# Import libraries

import pandas as pd
import numpy as np
import os

In [2]:
path = r'/Users/nurgul/Instacart Basket Analysis'

In [3]:
# Imported Data set ords_prods_merge_derived.pkl
df_ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_merge_derived.pkl'))

In [4]:
# Create a subset
df = df_ords_prods_merge[:1000000]

In [5]:
df.shape

(1000000, 20)

In [6]:
df.head(10)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,hour_of_day_ordered,days_since_prior_order,add_to_cart_order,reordered,_merge,merge_indicator,price_range_loc,busiest_dat,Busiest_day,busiest_day,busiest_peroid_of_the_day
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Most orders
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Average orders
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,both,Mid-range product,Busiest day,Busiest day,Busiest days,Average orders
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,both,both,Mid-range product,Regulary busy,Regulary busy,Slowest days,Most orders
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,both,Mid-range product,Least busy,Least busy,Slowest days,Average orders
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,26.0,7,0,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Average orders
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,30.0,2,0,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Most orders
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,30.0,1,0,both,both,Mid-range product,Regulary busy,Regulary busy,Slowest days,Most orders
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,19.0,1,0,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Average orders
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,15.0,2,1,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Most orders

In [7]:
df.drop(columns=['busiest_dat', 'aisle_id'])

,product_id,product_name,department_id,prices,order_id,user_id,order_number,orders_day_of_week,hour_of_day_ordered,days_since_prior_order,add_to_cart_order,reordered,_merge,merge_indicator,price_range_loc,Busiest_day,busiest_day,busiest_peroid_of_the_day
0,1,Chocolate Sandwich Cookies,19,5.8,3139998,138,28,6,11,3.0,5,0,both,both,Mid-range product,Regulary busy,Regulary busy,Most orders
1,1,Chocolate Sandwich Cookies,19,5.8,1977647,138,30,6,17,20.0,1,1,both,both,Mid-range product,Regulary busy,Regulary busy,Average orders
2,1,Chocolate Sandwich Cookies,19,5.8,389851,709,2,0,21,6.0,20,0,both,both,Mid-range product,Busiest day,Busiest days,Average orders
3,1,Chocolate Sandwich Cookies,19,5.8,652770,764,1,3,13,NaN,10,0,both,both,Mid-range product,Regulary busy,Slowest days,Most orders
4,1,Chocolate Sandwich Cookies,19,5.8,1813452,764,3,4,17,9.0,11,1,both,both,Mid-range product,Least busy,Slowest days,Average orders
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2078,Unsalted Pure Irish Butter,16,13.5,2280887,102527,25,6,14,6.0,1,1,both,both,Mid-range product,Regulary busy,Regulary busy,Most orders
999996,2078,Unsalted Pure Irish Butter,16,13.5,3310791,102530,1,4,17,NaN,13,0,both,both,Mid-range product,Least busy,Slowest days,Average orders
999997,2078,Unsalted Pure Irish Butter,16,13.5,1704867,102530,2,2,17,30.0,4,1,both,both,Mid-range product,Regulary busy,Regulary busy,Average orders
999998,2078,Unsalted Pure Irish Butter,16,13.5,629818,102530,3,6,18,4.0,3,1,both,both,Mid-range product,Regulary busy,Regulary busy,Average orders
999999,2078,Unsalted Pure Irish Butter,16,13.5,2328893,102544,5,5,9,1.0,1,0,both,both,Mid-range product,Regulary busy,Regulary busy,Most orders

### Grouping Data

In [8]:
# Splitting data into groups based on product name
df.groupby('product_name')

### Aggregating Data with agg()

#### Performing single aggregation

In [9]:
# Splitting data into groups based on department_id
df.groupby('department_id').agg ({'order_number':['mean']})

              order_number
                      mean
department_id
1                15.577493
2                17.320781
3                16.084944
4                17.530458
5                14.763075
6                16.658449
7                17.031590
8                15.076662
9                15.447580
10               18.681852
11               15.447411
12               14.327957
13               16.548642
14               16.960241
15               16.121948
16               17.803851
17               15.593633
18               19.674252
19               16.899756
20               16.255442
21               25.535479

In [10]:
df.groupby('department_id') ['order_number'].mean()

department_id
1     15.577493
2     17.320781
3     16.084944
4     17.530458
5     14.763075
6     16.658449
7     17.031590
8     15.076662
9     15.447580
10    18.681852
11    15.447411
12    14.327957
13    16.548642
14    16.960241
15    16.121948
16    17.803851
17    15.593633
18    19.674252
19    16.899756
20    16.255442
21    25.535479
Name: order_number, dtype: float64

#### Performing multiple aggregations

In [11]:
df.groupby('department_id').agg ({'order_number':['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1                15.577493   1  99
2                17.320781   1  96
3                16.084944   1  99
4                17.530458   1  99
5                14.763075   1  99
6                16.658449   1  99
7                17.031590   1  99
8                15.076662   1  98
9                15.447580   1  99
10               18.681852   1  99
11               15.447411   1  99
12               14.327957   1  99
13               16.548642   1  99
14               16.960241   1  99
15               16.121948   1  99
16               17.803851   1  99
17               15.593633   1  99
18               19.674252   1  99
19               16.899756   1  99
20               16.255442   1  99
21               25.535479   1  98

### Aggregating Data with transform()

In [12]:
#Creating max_order column,grouping by user_id, applying transform function on order_number
df_ords_prods_merge['max_order']=df_ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

/var/folders/b1/dcgm49cs1dx0p3lkf95fklvr0000gp/T/ipykernel_72655/936315459.py:2: FutureWarning: The provided callable <function amax at 0x105d85620> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df_ords_prods_merge['max_order']=df_ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [13]:
#Checking results
df_ords_prods_merge.head(15)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,hour_of_day_ordered,...,add_to_cart_order,reordered,_merge,merge_indicator,price_range_loc,busiest_dat,Busiest_day,busiest_day,busiest_peroid_of_the_day,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,5,0,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Most orders,32
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,1,1,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Average orders,32
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,20,0,both,both,Mid-range product,Busiest day,Busiest day,Busiest days,Average orders,5
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,10,0,both,both,Mid-range product,Regulary busy,Regulary busy,Slowest days,Most orders,3
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,11,1,both,both,Mid-range product,Least busy,Least busy,Slowest days,Average orders,3
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,...,7,0,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Average orders,26
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,...,2,0,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Most orders,9
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,...,1,0,both,both,Mid-range product,Regulary busy,Regulary busy,Slowest days,Most orders,12
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,...,1,0,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Average orders,20
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,...,2,1,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Most orders,20
10,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,1,5,11,...,1,0,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Most orders,10
11,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,36,3,13,...,1,0,both,both,Mid-range product,Regulary busy,Regulary busy,Slowest days,Most orders,43
12,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,38,4,13,...,3,1,both,both,Mid-range product,Least busy,Least busy,Slowest days,Most orders,43
13,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,39,2,12,...,4,1,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Most orders,43
14,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,6,3,10,...,8,0,both,both,Mid-range product,Regulary busy,Regulary busy,Slowest days,Most orders,13

In [14]:
pd.options.display.max_rows=None

In [15]:
df_ords_prods_merge.head(100)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,hour_of_day_ordered,...,add_to_cart_order,reordered,_merge,merge_indicator,price_range_loc,busiest_dat,Busiest_day,busiest_day,busiest_peroid_of_the_day,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,5,0,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Most orders,32
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,1,1,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Average orders,32
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,20,0,both,both,Mid-range product,Busiest day,Busiest day,Busiest days,Average orders,5
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,10,0,both,both,Mid-range product,Regulary busy,Regulary busy,Slowest days,Most orders,3
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,11,1,both,both,Mid-range product,Least busy,Least busy,Slowest days,Average orders,3
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,...,7,0,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Average orders,26
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,...,2,0,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Most orders,9
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,...,1,0,both,both,Mid-range product,Regulary busy,Regulary busy,Slowest days,Most orders,12
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,...,1,0,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Average orders,20
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,...,2,1,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Most orders,20
10,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,1,5,11,...,1,0,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Most orders,10
11,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,36,3,13,...,1,0,both,both,Mid-range product,Regulary busy,Regulary busy,Slowest days,Most orders,43
12,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,38,4,13,...,3,1,both,both,Mid-range product,Least busy,Least busy,Slowest days,Most orders,43
13,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,39,2,12,...,4,1,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Most orders,43
14,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,6,3,10,...,8,0,both,both,Mid-range product,Regulary busy,Regulary busy,Slowest days,Most orders,13
15,1,Chocolate Sandwich Cookies,61,19,5.8,186761,1494,7,2,8,...,18,1,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Average orders,13
16,1,Chocolate Sandwich Cookies,61,19,5.8,317121,1494,9,5,8,...,12,1,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Average orders,13
17,1,Chocolate Sandwich Cookies,61,19,5.8,200390,1540,4,2,0,...,10,0,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Fewest orders,28
18,1,Chocolate Sandwich Cookies,61,19,5.8,374436,1540,5,1,21,...,9,1,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Average orders,28
19,1,Chocolate Sandwich Cookies,61,19,5.8,2920553,1540,6,1,0,...,9,1,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Fewest orders,28
20,1,Chocolate Sandwich Cookies,61,19,5.8,2813049,1540,7,2,2,...,7,1,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Fewest orders,28
21,1,Chocolate Sandwich Cookies,61,19,5.8,2365998,1540,8,1,23,...,6,1,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Fewest orders,28
22,1,Chocolate Sandwich Cookies,61,19,5.8,1604797,1540,9,1,3,...,6,1,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Fewest orders,28
23,1,Chocolate Sandwich Cookies,61,19,5.8,2799665,1540,14,1,14,...,10,1,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Most orders,28
24,1,Chocolate Sandwich Cookies,61,19,5.8,2228851,1540,15,1,14,...,3,1,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Most orders,28
25,1,Chocolate Sandwich Cookies,61,19,5.8,2337422,1540,18,0,21,...,5,1,both,both,Mid-range product,Busiest day,Busiest day,Busiest days,Average orders,28
26,1,Chocolate Sandwich Cookies,61,19,5.8,2699008,1540,19,0,22,...,11,1,both,both,Mid-range product,Busiest day,Busiest day,Busiest days,Average orders,28
27,1,Chocolate Sandwich Cookies,61,19,5.8,1914830,1540,20,0,22,...,11,1,both,both,Mid-range product,Busiest day,Busiest day,Busiest days,Average orders,28
28,1,Chocolate Sandwich Cookies,61,19,5.8,783503,1540,21,0,20,...,5,1,both,both,Mid-range product,Busiest day,Busiest day,Busiest days,Average orders,28
29,1,Chocolate Sandwich Cookies,61,19,5.8,2500516,1540,22,0,22,...,15,1,both,both,Mid-range product,Busiest day,Busiest day,Busiest days,Average orders,28
30,1,Chocolate Sandwich Cookies,61,19,5.8,716845,1540,24,4,22,...,4,1,both,both,Mid-range product,Least busy,Least busy,Slowest days,Average orders,28
31,1,Chocolate Sandwich Cookies,61,19,5.8,1955535,1540,25,6,19,...,6,1,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Average orders,28
32,1,Chocolate Sandwich Cookies,61,19,5.8,1424793,1540,27,1,1,...,1,1,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Fewest orders,28
33,1,Chocolate Sandwich Cookies,61,19,5.8,749498,1540,28,0,21,...,1,1,both,both,Mid-range product,Busiest day,Busiest day,Busiest days,Average orders,28
34,1,Chocolate Sandwich Cookies,61,19,5.8,2434812,1598,1,2,12,...,2,0,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Most orders,4
35,1,Chocolate Sandwich Cookies,61,19,5.8,1531889,1598,2,2,10,...,2,1,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Most orders,4
36,1,Chocolate Sandwich Cookies,61,19,5.8,726947,1598,3,4,17,...,3,1,both,both,Mid-range product,Least busy,Least busy,Slowest days,Average orders,4
37,1,Chocolate Sandwich Cookies,61,19,5.8,627615,1647,1,1,9,...,1,0,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Most orders,10
38,1,Chocolate Sandwich Cookies,61,19,5.8,2507439,1647,4,0,13,...,6,1,both,both,Mid-range product,Busiest day,Busiest day,Busiest days,Most orders,10
39,1,Chocolate Sandwich Cookies,61,19,5.8,1152609,1647,6,1,9,...,3,1,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Most orders,10
40,1,Chocolate Sandwich Cookies,61,19,5.8,1048339,1647,8,0,17,...,10,1,both,both,Mid-range product,Busiest day,Busiest day,Busiest days,Average orders,10
41,1,Chocolate Sandwich Cookies,61,19,5.8,2818381,1647,9,4,15,...,1,1,both,both,Mid-range product,Least busy,Least busy,Slowest days,Most orders,10
42,1,Chocolate Sandwich Cookies,61,19,5.8,2722928,2833,1,0,14,...,12,0,both,both,Mid-range product,Busiest day,Busiest day,Busiest days,Most orders,10
43,1,Chocolate Sandwich Cookies,61,19,5.8,1482338,2850,7,1,16,...,10,0,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Most orders,23
44,1,Chocolate Sandwich Cookies,61,19,5.8,2311344,2857,24,1,8,...,5,0,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Average orders,25
45,1,Chocolate Sandwich Cookies,61,19,5.8,812943,3010,5,3,10,...,11,0,both,both,Mid-range product,Regulary busy,Regulary busy,Slowest days,Most orders,13
46,1,Chocolate Sandwich Cookies,61,19,5.8,256839,3029,1,2,20,...,8,0,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Average orders,5
47,1,Chocolate Sandwich Cookies,61,19,5.8,2192488,3395,4,2,10,...,7,0,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Most orders,6
48,1,Chocolate Sandwich Cookies,61,19,5.8,207661,3904,1,1,14,...,2,0,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Most orders,3
49,1,Chocolate Sandwich Cookies,61,19,5.8,1394659,4006,2,1,10,...,8,0,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Most orders,42
50,1,Chocolate Sandwich Cookies,61,19,5.8,2353526,4006,3,1,10,...,2,1,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Most orders,42
51,1,Chocolate Sandwich Cookies,61,19,5.8,2269226,4006,5,3,13,...,6,1,both,both,Mid-range product,Regulary busy,Regulary busy,Slowest days,Most orders,42
52,1,Chocolate Sandwich Cookies,61,19,5.8,367316,4006,9,2,11,...,3,1,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Most orders,42
53,1,Chocolate Sandwich Cookies,61,19,5.8,1448367,4006,12,1,11,...,2,1,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Most orders,42
54,1,Chocolate Sandwich Cookies,61,19,5.8,19989,4122,11,2,7,...,1,0,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Average orders,40
55,1,Chocolate Sandwich Cookies,61,19,5.8,2735922,4141,2,0,8,...,2,0,both,both,Mid-range product,Busiest day,Busiest day,Busiest days,Average orders,9
56,1,Chocolate Sandwich Cookies,61,19,5.8,2469422,4343,1,1,16,...,9,0,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Most orders,4
57,1,Chocolate Sandwich Cookies,61,19,5.8,3185558,4553,3,5,16,...,1,0,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Most orders,4
58,1,Chocolate Sandwich Cookies,61,19,5.8,350540,4845,6,0,13,...,7,0,both,both,Mid-range product,Busiest day,Busiest day,Busiest days,Most orders,14
59,1,Chocolate Sandwich Cookies,61,19,5.8,513100,6866,1,4,15,...,11,0,both,both,Mid-range product,Least busy,Least busy,Slowest days,Most orders,6
60,1,Chocolate Sandwich Cookies,61,19,5.8,2081405,7275,5,2,23,...,6,0,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Fewest orders,8
61,1,Chocolate Sandwich Cookies,61,19,5.8,2209807,7669,3,3,15,...,5,0,both,both,Mid-range product,Regulary busy,Regulary busy,Slowest days,Most orders,21
62,1,Chocolate Sandwich Cookies,61,19,5.8,921798,7669,4,1,17,...,6,1,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Average orders,21
63,1,Chocolate Sandwich Cookies,61,19,5.8,2540226,7669,20,1,8,...,3,1,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Average orders,21
64,1,Chocolate Sandwich Cookies,61,19,5.8,2265792,7981,9,2,15,...,2,0,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Most orders,31
65,1,Chocolate Sandwich Cookies,61,19,5.8,3357714,7981,13,0,23,...,1,1,both,both,Mid-range product,Busiest day,Busiest day,Busiest days,Fewest orders,31
66,1,Chocolate Sandwich Cookies,61,19,5.8,1186573,7981,14,2,23,...,1,1,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Fewest orders,31
67,1,Chocolate Sandwich Cookies,61,19,5.8,3209740,7981,24,2,13,...,2,1,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Most orders,31
68,1,Chocolate Sandwich Cookies,61,19,5.8,138748,7981,30,3,16,...,2,1,both,both,Mid-range product,Regulary busy,Regulary busy,Slowest days,Most orders,31
69,1,Chocolate Sandwich Cookies,61,19,5.8,2027157,8703,34,4,13,...,13,0,both,both,Mid-range product,Least busy,Least busy,Slowest days,Most orders,99
70,1,Chocolate Sandwich Cookies,61,19,5.8,3052954,8723,4,3,10,...,2,0,both,both,Mid-range product,Regulary busy,Regulary busy,Slowest days,Most orders,36
71,1,Chocolate Sandwich Cookies,61,19,5.8,1486756,8735,8,4,11,...,2,0,both,both,Mid-range product,Least busy,Least busy,Slowest days,Most orders,9
72,1,Chocolate Sandwich Cookies,61,19,5.8,632514,9293,2,0,12,...,2,0,both,both,Mid-range product,Busiest day,Busiest day,Busiest days,Most orders,5
73,1,Chocolate Sandwich Cookies,61,19,5.8,1253470,9293,3,3,13,...,1,1,both,both,Mid-range product,Regulary busy,Regulary busy,Slowest days,Most orders,5
74,1,Chocolate Sandwich Cookies,61,19,5.8,837303,9467,1,0,17,...,11,0,both,both,Mid-range product,Busiest day,Busiest day,Busiest days,Average orders,5
75,1,Chocolate Sandwich Cookies,61,19,5.8,2734881,9694,2,0,17,...,3,0,both,both,Mid-range product,Busiest day,Busiest day,Busiest days,Average orders,23
76,1,Chocolate Sandwich Cookies,61,19,5.8,2164394,9694,4,4,18,...,2,1,both,both,Mid-range product,Least busy,Least busy,Slowest days,Average orders,23
77,1,Chocolate Sandwich Cookies,61,19,5.8,3354551,9694,5,4,15,...,1,1,both,both,Mid-range product,Least busy,Least busy,Slowest days,Most orders,23
78,1,Chocolate Sandwich Cookies,61,19,5.8,1381165,9694,6,4,21,...,2,1,both,both,Mid-range product,Least busy,Least busy,Slowest days,Average orders,23
79,1,Chocolate Sandwich Cookies,61,19,5.8,2809438,9694,7,4,18,...,1,1,both,both,Mid-range product,Least busy,Least busy,Slowest days,Average orders,23
80,1,Chocolate Sandwich Cookies,61,19,5.8,425352,9694,10,4,7,...,4,1,both,both,Mid-range product,Least busy,Least busy,Slowest days,Average orders,23
81,1,Chocolate Sandwich Cookies,61,19,5.8,2453441,9694,14,4,22,...,1,1,both,both,Mid-range product,Least busy,Least busy,Slowest days,Average orders,23
82,1,Chocolate Sandwich Cookies,61,19,5.8,1189695,9694,15,4,16,...,1,1,both,both,Mid-range product,Least busy,Least busy,Slowest days,Most orders,23
83,1,Chocolate Sandwich Cookies,61,19,5.8,1759231,9694,16,4,15,...,2,1,both,both,Mid-range product,Least busy,Least busy,Slowest days,Most orders,23
84,1,Chocolate Sandwich Cookies,61,19,5.8,482648,9694,20,4,13,...,1,1,both,both,Mid-range product,Least busy,Least busy,Slowest days,Most orders,23
85,1,Chocolate Sandwich Cookies,61,19,5.8,2201348,9694,22,4,14,...,7,1,both,both,Mid-range product,Least busy,Least busy,Slowest days,Most orders,23
86,1,Chocolate Sandwich Cookies,61,19,5.8,3351592,9848,17,4,18,...,16,0,both,both,Mid-range product,Least busy,Least busy,Slowest days,Average orders,23
87,1,Chocolate Sandwich Cookies,61,19,5.8,2164672,10113,6,4,18,...,5,0,both,both,Mid-range product,Least busy,Least busy,Slowest days,Average orders,11
88,1,Chocolate Sandwich Cookies,61,19,5.8,1526735,10315,1,0,16,...,2,0,both,both,Mid-range product,Busiest day,Busiest day,Busiest days,Most orders,5
89,1,Chocolate Sandwich Cookies,61,19,5.8,2057892,10479,22,1,16,...,8,0,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Most orders,22
90,1,Chocolate Sandwich Cookies,61,19,5.8,356685,10708,4,2,14,...,15,0,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Most orders,21
91,1,Chocolate Sandwich Cookies,61,19,5.8,1592736,10708,8,2,14,...,9,1,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Most orders,21
92,1,Chocolate Sandwich Cookies,61,19,5.8,3125810,10789,10,0,21,...,1,0,both,both,Mid-range product,Busiest day,Busiest day,Busiest days,Average orders,36
93,1,Chocolate Sandwich Cookies,61,19,5.8,846661,10789,11,0,19,...,4,1,both,both,Mid-range product,Busiest day,Busiest day,Busiest days,Average orders,36
94,1,Chocolate Sandwich Cookies,61,19,5.8,2363761,10789,16,2,16,...,2,1,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Most orders,36
95,1,Chocolate Sandwich Cookies,61,19,5.8,602103,10831,8,3,11,...,5,0,both,both,Mid-range product,Regulary busy,Regulary busy,Slowest days,Most orders,10
96,1,Chocolate Sandwich Cookies,61,19,5.8,49629,11119,18,1,14,...,1,0,both,both,Mid-range product,Regulary busy,Regulary busy,Busiest days,Most orders,23
97,1,Chocolate Sandwich Cookies,61,19,5.8,317888,11186,13,5,16,...,8,0,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Most orders,26
98,1,Chocolate Sandwich Cookies,61,19,5.8,682486,11243,16,3,13,...,2,0,both,both,Mid-range product,Regulary busy,Regulary busy,Slowest days,Most orders,43
99,1,Chocolate Sandwich Cookies,61,19,5.8,2861386,11448,10,2,15,...,6,0,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Most orders,21

### Deriving Columns with loc()

In [16]:
df_ords_prods_merge.loc[df_ords_prods_merge['max_order'] > 40, 'loyalty_flag']='Loyal customer'

/var/folders/b1/dcgm49cs1dx0p3lkf95fklvr0000gp/T/ipykernel_72655/2537120548.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Loyal customer' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_ords_prods_merge.loc[df_ords_prods_merge['max_order'] > 40, 'loyalty_flag']='Loyal customer'

In [17]:
df_ords_prods_merge.loc[(df_ords_prods_merge['max_order'] <= 40) & (df_ords_prods_merge['max_order'] > 10), 'loyalty_flag']='Regular customer'

In [18]:
df_ords_prods_merge.loc[df_ords_prods_merge['max_order'] <= 10, 'loyalty_flag']='New customer'

In [19]:
df_ords_prods_merge['loyalty_flag'].value_counts(dropna=False)

loyalty_flag
Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: count, dtype: int64

In [20]:
df_ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0       138  Regular customer            28
1       138  Regular customer            30
2       709      New customer             2
3       764      New customer             1
4       764      New customer             3
5       777  Regular customer            16
6       825      New customer             3
7       910  Regular customer            12
8      1052  Regular customer            10
9      1052  Regular customer            15
10     1379      New customer             1
11     1480    Loyal customer            36
12     1480    Loyal customer            38
13     1480    Loyal customer            39
14     1494  Regular customer             6
15     1494  Regular customer             7
16     1494  Regular customer             9
17     1540  Regular customer             4
18     1540  Regular customer             5
19     1540  Regular customer             6
20     1540  Regular customer             7
21     1540  Regular customer             8
22     1540  Regular customer             9
23     1540  Regular customer            14
24     1540  Regular customer            15
25     1540  Regular customer            18
26     1540  Regular customer            19
27     1540  Regular customer            20
28     1540  Regular customer            21
29     1540  Regular customer            22
30     1540  Regular customer            24
31     1540  Regular customer            25
32     1540  Regular customer            27
33     1540  Regular customer            28
34     1598      New customer             1
35     1598      New customer             2
36     1598      New customer             3
37     1647      New customer             1
38     1647      New customer             4
39     1647      New customer             6
40     1647      New customer             8
41     1647      New customer             9
42     2833      New customer             1
43     2850  Regular customer             7
44     2857  Regular customer            24
45     3010  Regular customer             5
46     3029      New customer             1
47     3395      New customer             4
48     3904      New customer             1
49     4006    Loyal customer             2
50     4006    Loyal customer             3
51     4006    Loyal customer             5
52     4006    Loyal customer             9
53     4006    Loyal customer            12
54     4122  Regular customer            11
55     4141      New customer             2
56     4343      New customer             1
57     4553      New customer             3
58     4845  Regular customer             6
59     6866      New customer             1

## Task 4.8.

### Step 2 find the aggregated mean of the “order_number” column grouped by “department_id” for the entire dataframe

In [21]:
df_ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,hour_of_day_ordered,...,reordered,_merge,merge_indicator,price_range_loc,busiest_dat,Busiest_day,busiest_day,busiest_peroid_of_the_day,max_order,loyalty_flag
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,0,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Most orders,32,Regular customer
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,1,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Average orders,32,Regular customer
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,0,both,both,Mid-range product,Busiest day,Busiest day,Busiest days,Average orders,5,New customer
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,0,both,both,Mid-range product,Regulary busy,Regulary busy,Slowest days,Most orders,3,New customer
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,1,both,both,Mid-range product,Least busy,Least busy,Slowest days,Average orders,3,New customer

### Grouping Data

In [22]:
# Splitting data into groups based on product name
df_ords_prods_merge.groupby('product_name')

In [23]:
# Splitting data into groups based on department_id
df_ords_prods_merge.groupby('department_id').agg ({'order_number':['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

### Step 3 Analyze the results.

Since the subset was limited to 1000000, it is understandable that the average slightly differs from the entire data frame. However, it is worth mentioning that department IDs "10" and "21" have a difference in average of more than 2.

### Step 4 Create a loyalty flag for existing customers using the transform() and loc() functions.

In [25]:
df_ords_prods_merge.groupby('loyalty_flag').agg ({'prices':['mean', 'min', 'max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.386336  1.0  99999.0
New customer      13.294670  1.0  99999.0
Regular customer  12.495717  1.0  99999.0

Step 5. Loyal customers seems to purhcase less expensive products, it might be the main reason they purchase more frequently.

### Step 6 Create a spending flag for each user based on the average price across all their orders

In [26]:
# Creating mean_spend column 
df_ords_prods_merge['mean_spend'] = df_ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

/var/folders/b1/dcgm49cs1dx0p3lkf95fklvr0000gp/T/ipykernel_72655/4264494920.py:2: FutureWarning: The provided callable <function mean at 0x105d86340> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df_ords_prods_merge['mean_spend'] = df_ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [27]:
df_ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,hour_of_day_ordered,...,_merge,merge_indicator,price_range_loc,busiest_dat,Busiest_day,busiest_day,busiest_peroid_of_the_day,max_order,loyalty_flag,mean_spend
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Most orders,32,Regular customer,6.935811
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,both,both,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Average orders,32,Regular customer,6.935811
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,both,both,Mid-range product,Busiest day,Busiest day,Busiest days,Average orders,5,New customer,7.930208
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,both,both,Mid-range product,Regulary busy,Regulary busy,Slowest days,Most orders,3,New customer,4.972414
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,both,both,Mid-range product,Least busy,Least busy,Slowest days,Average orders,3,New customer,4.972414

In [29]:
# Creating column with spender flag based on criteria
df_ords_prods_merge.loc[df_ords_prods_merge['mean_spend'] > 10, 'spender_flag']='Low spender'

In [30]:
df_ords_prods_merge.loc[df_ords_prods_merge['mean_spend'] <= 10, 'spender_flag']='High spender'

In [31]:
df_ords_prods_merge['spender_flag'].value_counts(dropna=False)

spender_flag
High spender    31770995
Low spender       633864
Name: count, dtype: int64

In [34]:
df_ords_prods_merge[['user_id', 'spender_flag', 'loyalty_flag']].head()

   user_id  spender_flag      loyalty_flag
0      138  High spender  Regular customer
1      138  High spender  Regular customer
2      709  High spender      New customer
3      764  High spender      New customer
4      764  High spender      New customer

### Step 7 Create an order frequency flag that marks the regularity of a user’s ordering behavior according to the median in the “days_since_prior_order” column.

In [35]:
# Creating median_order_frequency column
df_ords_prods_merge['median_order_frequency'] = df_ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

/var/folders/b1/dcgm49cs1dx0p3lkf95fklvr0000gp/T/ipykernel_72655/2940632875.py:2: FutureWarning: The provided callable <function median at 0x105ecc680> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df_ords_prods_merge['median_order_frequency'] = df_ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [36]:
df_ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,hour_of_day_ordered,...,price_range_loc,busiest_dat,Busiest_day,busiest_day,busiest_peroid_of_the_day,max_order,loyalty_flag,mean_spend,spender_flag,median_order_frequency
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Most orders,32,Regular customer,6.935811,High spender,8.0
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,Mid-range product,Regulary busy,Regulary busy,Regulary busy,Average orders,32,Regular customer,6.935811,High spender,8.0
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,Mid-range product,Busiest day,Busiest day,Busiest days,Average orders,5,New customer,7.930208,High spender,8.0
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,Mid-range product,Regulary busy,Regulary busy,Slowest days,Most orders,3,New customer,4.972414,High spender,9.0
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,Mid-range product,Least busy,Least busy,Slowest days,Average orders,3,New customer,4.972414,High spender,9.0

In [52]:
df_ords_prods_merge.loc[df_ords_prods_merge['median_order_frequency'] > 20, 'order_frequency_flag']='Non-frequent custome'

In [51]:
df_ords_prods_merge.loc[(df_ords_prods_merge['median_order_frequency'] > 10) & (df_ords_prods_merge['median_order_frequency'] <= 20), 'order_frequency_flag']='Regular customer'

In [50]:
df_ords_prods_merge.loc[df_ords_prods_merge['median_order_frequency'] <= 10, 'order_frequency_flag']='Frequent custome'

In [53]:
df_ords_prods_merge['order_frequency_flag'].value_counts(dropna=False)

order_frequency_flag
Frequent custome        21559853
Regular customer         7208564
Non-frequent custome     3636437
NaN                            5
Name: count, dtype: int64

In [54]:
df_ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,hour_of_day_ordered,...,busiest_dat,Busiest_day,busiest_day,busiest_peroid_of_the_day,max_order,loyalty_flag,mean_spend,spender_flag,median_order_frequency,order_frequency_flag
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,Regulary busy,Regulary busy,Regulary busy,Most orders,32,Regular customer,6.935811,High spender,8.0,Frequent custome
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,Regulary busy,Regulary busy,Regulary busy,Average orders,32,Regular customer,6.935811,High spender,8.0,Frequent custome
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,Busiest day,Busiest day,Busiest days,Average orders,5,New customer,7.930208,High spender,8.0,Frequent custome
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,Regulary busy,Regulary busy,Slowest days,Most orders,3,New customer,4.972414,High spender,9.0,Frequent custome
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,Least busy,Least busy,Slowest days,Average orders,3,New customer,4.972414,High spender,9.0,Frequent custome

### Step 9 Export your dataframe

In [60]:
df_ords_prods_merge.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'ords_prods_merge_updated.pkl'))